variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - ReadMe.md
      - ./**/ReadMe.md

pr:
  branches:
    include:
      - master
  paths:
    include:
      - database
    exclude:
      - source
      - tests
      - ReadMe.md
      - ./**/ReadMe.md

pool:
  vmImage: ubuntu-latest
steps:
  - bash: echo "I'm DB build"
