variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

# We don't need a CI trigger here, as the pipeline trigger starts this pipeline for master anyway.
# But we need to setup a PR trigger, to exclude some paths.
trigger: none

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - database
      - ReadMe.md
      - ./**/ReadMe.md

# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#configure-pipeline-resource-triggers
resources:
  pipelines:
    - pipeline: db-build
      source: Pipeline-Trigger-Test-DB
      trigger: true

pool:
  vmImage: ubuntu-latest
steps:
  - bash: echo "I'm O/R build"
